### PR TITLE
kata-deploy: Add runtime config for crio if it does not exist

### LINKED ISSUE #374: kata-deploy: Multiple entries for "crio.runtime.runtimes.kata-qemu" added to cri-o conf file
Not sure what sequence of steps caused it, but ended up with multiple "crio.runtime.runtimes.kata-qemu"
and "crio.runtime.runtimes.kata-fc" in the cri-o conf file, causing cri-o to fail to start.
kata-deploy should check for the runtime entries, if they are already present before adding them.

### PR DESCRIPTION
**Pull request by amshinde**
Rather than add the config for kata-qemu and kata-fc unconditionally,
the script now checks if the runtime config exists.
If it exists, then do not chnage the path for the runtime.
The user may have configured this to a specific path for testing
local chnages.

Fixes #374

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

File: kata-deploy/scripts/kata-deploy.sh [hunk 1]
```diff
@@ -57,10 +57,13 @@ function configure_crio() {
 	# backup the CRIO.conf only if a backup doesn't already exist (don't override original)
 	cp -n "$crio_conf_file" "$crio_conf_file_backup"
 
-	cat <<EOT | tee -a "$crio_conf_file"
+	grep -Fq '[crio.runtime.runtimes.kata-qemu]' $crio_conf_file \
```
Comment (amshinde) [inline kata-deploy/scripts/kata-deploy.sh]: This PR avoids overriding the configuration if it already exists. Not sure, what the best strategy should be.

Comment (jodh-intel) [inline kata-deploy/scripts/kata-deploy.sh]: Nit: You could add variables for the multiple instances of `[crio.runtime.runtimes.kata-qemu]` and `[crio.runtime.runtimes.kata-fc]`.

Comment (egernst) [reply kata-deploy/scripts/kata-deploy.sh]: I wonder if an error being returned would be wise here? I’m not sure best way to handle, but silently overwriting and silently ignoring aren’t great.

Comment (krsna1729) [reply kata-deploy/scripts/kata-deploy.sh]: Overwrite just like network lifecycle. Document the behavior?

Comment (jodh-intel) [reply kata-deploy/scripts/kata-deploy.sh]: We backup the file 2 lines above, so... ? :)

Comment (egernst) [reply kata-deploy/scripts/kata-deploy.sh]: @amshinde can you follow @krsna1729's recommendation?  Since we save the file already, I think overwriting does make sense, put perhaps throw a warning

**Comment by egernst** [comment]
Looks good to me overall, and thank you for the PR @amshinde .  I think overwriting makes most sense -- can you make this change, and then i'm happy to see it merged.

**Comment by amshinde** [comment]
@mcastelino @krsna1729 @jodh-intel @egernst I have pushed changes so that the script  overwrites the runtime configuration if it exists and adds if not present. PTAL.

File: kata-deploy/scripts/kata-deploy.sh [hunk 2]
```diff
@@ -57,10 +57,18 @@ function configure_crio() {
 	# backup the CRIO.conf only if a backup doesn't already exist (don't override original)
 	cp -n "$crio_conf_file" "$crio_conf_file_backup"
 
-	cat <<EOT | tee -a "$crio_conf_file"
+	grep -q '^\[crio.runtime.runtimes.kata-qemu\]' $crio_conf_file \
+	&& echo "Configuration exists for crio.runtime.runtimes.kata-qemu, overwriting" \
+	&& sed -i '/\[crio.runtime.runtimes.kata-qemu\]/,+1s/runtime_path.*/runtime_path = "\/opt\/kata\/bin\/kata-qemu"/' $crio_conf_file \
```
Comment (jodh-intel) [inline kata-deploy/scripts/kata-deploy.sh]: Nits:

- Now you've got three refs to `crio.runtime.runtimes.kata-qemu`, I'd be highly tempted to turn this into a variable.
- You can simplify the sed by using `sed -i "!from!to!"` to avoid having to escape the path slashes. But in fact, why not create a variable for the path so you can just do `sed -i "/blah/$path/"`.

Comment (amshinde) [reply kata-deploy/scripts/kata-deploy.sh]: @jodh-intel Done!

**Comment by jodh-intel** [comment]
Thanks @amshinde.

CI restarted and more reviews required over here... ;)

**Comment by amshinde** [comment]
@mcastelino @sboeuf Can you take a look, so that this can be merged.

**Comment by amshinde** [comment]
@jodh-intel Can we merge this?
